server:
  port: 8000

spring:
  application:
    name: happynode-gateway # 应用名称
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 10.0.0.201:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true # 启用服务发现
        group: default # 所属组
        namespace: happynode # 命名空间
        server-addr: 10.0.0.201:8848 # Nacos 服务器地址
    gateway:
      routes:
        - id: auth
          uri: lb://happynode-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1