server:
  port: 8000
spring:
  application:
    name: happynode-gateway # 应用名称
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 10.0.0.204:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true # 启用服务发现
        group: default # 所属组
        namespace: 1c1ad03a-6534-4baf-9f4d-de1d36b791db # 命名空间
        server-addr: 10.0.0.204:8848 # Nacos 服务器地址
      config:
        file-extension: yaml
        namespace: 1c1ad03a-6534-4baf-9f4d-de1d36b791db
        refresh-enabled: true
  config:
    import:
      - nacos:happynode-redis?group=common
      - nacos:happynode-sa-token?group=common
      - nacos:happynode-gateway-dev?group=gateway
management:
  endpoints:
    web:
      exposure:
        include: refresh   # 开放 refresh 端点
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug

