server:
  port: 8080 # 项目启动的端口
spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
  application:
    name: happynode-auth
  cloud:
    nacos:
      server-addr: 10.0.0.204:8848
      username: nacos
      password: nacos
      config:
        file-extension: yaml
        refresh-enabled: true # 启用动态刷新
        namespace: 1c1ad03a-6534-4baf-9f4d-de1d36b791db
      discovery:
        namespace: 1c1ad03a-6534-4baf-9f4d-de1d36b791db
        group: default
  config:
    import:
      - nacos:happynode-redis?group=common
      - nacos:happynode-aliyun?group=common
management:
  endpoints:
    web:
      exposure:
        include: refresh   # 开放 refresh 端点
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  active-timeout: -1
  timeout: 25920000
  is-share: true
  is-concurrent: true
  token-style: random-128
  is-log: true
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug