<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.danby</groupId>
        <artifactId>happy-node</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>com.danby.happynode.note</groupId>
    <artifactId>happynode-note</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>happynode-note-api</module>
        <module>happynode-note-biz</module>
    </modules>

</project>